# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: dashboard.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'dashboard.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x64\x61shboard.proto\x12\x0e\x63rio_dashboard\"\x11\n\x0fShutdownRequest\"=\n\x10ShutdownResponse\x12\x12\n\nerror_code\x18\x01 \x01(\x05\x12\x15\n\rerror_message\x18\x02 \x01(\t2a\n\x10\x44\x61shboardControl\x12M\n\x08Shutdown\x12\x1f.crio_dashboard.ShutdownRequest\x1a .crio_dashboard.ShutdownResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'dashboard_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SHUTDOWNREQUEST']._serialized_start=35
  _globals['_SHUTDOWNREQUEST']._serialized_end=52
  _globals['_SHUTDOWNRESPONSE']._serialized_start=54
  _globals['_SHUTDOWNRESPONSE']._serialized_end=115
  _globals['_DASHBOARDCONTROL']._serialized_start=117
  _globals['_DASHBOARDCONTROL']._serialized_end=214
# @@protoc_insertion_point(module_scope)
