# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import dashboard_pb2 as dashboard__pb2

GRPC_GENERATED_VERSION = '1.84.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in dashboard_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DashboardControlStub:
    """Service for controlling the CompactRIO Dashboard server.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Shutdown = channel.unary_unary(
                '/crio_dashboard.DashboardControl/Shutdown',
                request_serializer=dashboard__pb2.ShutdownRequest.SerializeToString,
                response_deserializer=dashboard__pb2.ShutdownResponse.FromString,
                _registered_method=True)


class DashboardControlServicer:
    """Service for controlling the CompactRIO Dashboard server.
    """

    def Shutdown(self, request, context):
        """Shuts down both the HTTP dashboard server and this gRPC server.
        Returns an error status code on failure; OK (0) on success.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DashboardControlServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Shutdown': grpc.unary_unary_rpc_method_handler(
                    servicer.Shutdown,
                    request_deserializer=dashboard__pb2.ShutdownRequest.FromString,
                    response_serializer=dashboard__pb2.ShutdownResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'crio_dashboard.DashboardControl', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('crio_dashboard.DashboardControl', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DashboardControl:
    """Service for controlling the CompactRIO Dashboard server.
    """

    @staticmethod
    def Shutdown(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/crio_dashboard.DashboardControl/Shutdown',
            dashboard__pb2.ShutdownRequest.SerializeToString,
            dashboard__pb2.ShutdownResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
